# Generated by Django 5.2.8 on 2026-01-16 12:45

from django.db import migrations

def populate_tarea_defaults(apps, schema_editor):
    # Obtener modelo Tarea desde el registry de la migración
    Tarea = apps.get_model('base', 'Tarea')

    # 1) descripcion: rellenar con cadena vacía donde sea NULL
    Tarea.objects.filter(descripcion__isnull=True).update(descripcion='')

    # 2) usuario (FK): intentar asignar el primer usuario existente;
    #    si no hay ninguno, crear un usuario "migration-user"
    from django.conf import settings

    user_label = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')
    try:
        app_label, model_name = user_label.split('.')
    except Exception:
        app_label, model_name = 'auth', 'User'

    UserModel = apps.get_model(app_label, model_name)

    first_user = UserModel.objects.first()
    if first_user is None:
        # intentar crear usando el manager por defecto; soporta tanto create_user como create
        manager = getattr(UserModel, '_default_manager', None) or getattr(UserModel, 'objects', None)
        try:
            create_user = getattr(manager, 'create_user', None)
            if callable(create_user):
                first_user = manager.create_user(username='migration-user', password='changeme123')
            else:
                first_user = manager.create(username='migration-user')
        except Exception:
            # fallback: crear con create directamente en el modelo (mínimos campos)
            first_user = UserModel.objects.create(username='migration-user')

    # Asignar el usuario a tareas que no tienen usuario (usamos pk para update)
    Tarea.objects.filter(usuario__isnull=True).update(usuario=first_user.pk)


def reverse_func(apps, schema_editor):
    # No revertimos los cambios automáticamente
    return

class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_tarea_defaults, reverse_func),
    ]