# Generated by Django 5.2.8 on 2026-01-16 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_populate_tarea_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarea",
            options={"ordering": ["completo", "-creado"]},
        ),
        migrations.AlterField(
            model_name="tarea",
            name="descripcion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
